name: docs
on:
  push:
    branches-ignore:
      - 'docs'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: build
        run: zig build docs

      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: zig-out/docs/getty
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
